ALTER TABLE wallets
    ADD COLUMN player_id VARCHAR(255),
    ADD COLUMN balance NUMERIC(19, 4) NOT NULL DEFAULT 0,
    ADD CONSTRAINT wallets_balance_non_negative CHECK (balance >= 0);

UPDATE wallets
SET player_id = id::text
WHERE player_id IS NULL;

ALTER TABLE wallets
    ALTER COLUMN player_id SET NOT NULL,
    ADD CONSTRAINT wallets_player_id_unique UNIQUE (player_id);

CREATE TABLE wallet_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES wallets (id),
    operation_type VARCHAR(10) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL CHECK (amount > 0),
    balance_after NUMERIC(19, 4) NOT NULL CHECK (balance_after >= 0),
    idempotency_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wallet_operations_type_check CHECK (operation_type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT wallet_operations_idempotency_unique UNIQUE (wallet_id, idempotency_key)
);

CREATE INDEX wallet_operations_wallet_created_at_index
    ON wallet_operations (wallet_id, created_at DESC, id DESC);
